/** @format */

const CountryData = [
	{ name: "Afghanistan", value: "AF" },
	{ name: "Aland Islands", value: "AX" },
	{ name: "Moldova, Republic of", value: "MD" },
	{ name: "Monaco", value: "MC" },
	{ name: "Mongolia", value: "MN" },
	{ name: "Montenegro", value: "ME" },
	{ name: "Montserrat", value: "MS" },
	{ name: "Morocco", value: "MA" },
	{ name: "Mozambique", value: "MZ" },
	{ name: "Myanmar", value: "MM" },
	{ name: "Namibia", value: "NA" },
	{ name: "Nauru", value: "NR" },
	{ name: "Nepal", value: "NP" },
	{ name: "Netherlands", value: "NL" },
	{ name: "Netherlands Antilles", value: "AN" },
	{ name: "New Caledonia", value: "NC" },
	{ name: "New Zealand", value: "NZ" },
	{ name: "Nicaragua", value: "NI" },
	{ name: "Niger", value: "NE" },
	{ name: "Nigeria", value: "NG" },
	{ name: "Niue", value: "NU" },
	{ name: "Norfolk Island", value: "NF" },
	{ name: "Northern Mariana Islands", value: "MP" },
	{ name: "Norway", value: "NO" },
	{ name: "Oman", value: "OM" },
	{ name: "Pakistan", value: "PK" },
	{ name: "Palau", value: "PW" },
	{ name: "Palestinian Territory, Occupied", value: "PS" },
	{ name: "Panama", value: "PA" },
	{ name: "Papua New Guinea", value: "PG" },
	{ name: "Paraguay", value: "PY" },
	{ name: "Peru", value: "PE" },
	{ name: "Philippines", value: "PH" },
	{ name: "Pitcairn", value: "PN" },
	{ name: "Poland", value: "PL" },
	{ name: "Portugal", value: "PT" },
	{ name: "Puerto Rico", value: "PR" },
	{ name: "Qatar", value: "QA" },
	{ name: "Reunion", value: "RE" },
	{ name: "Romania", value: "RO" },
	{ name: "Russian Federation", value: "RU" },
	{ name: "Rwanda", value: "RW" },
	{ name: "Saint Barthelemy", value: "BL" },
	{ name: "Saint Helena", value: "SH" },
	{ name: "Saint Kitts and Nevis", value: "KN" },
	{ name: "Saint Lucia", value: "LC" },
	{ name: "Saint Martin", value: "MF" },
	{ name: "Saint Pierre and Miquelon", value: "PM" },
	{ name: "Saint Vincent and the Grenadines", value: "VC" },
	{ name: "Samoa", value: "WS" },
	{ name: "San Marino", value: "SM" },
	{ name: "Sao Tome and Principe", value: "ST" },
	{ name: "Saudi Arabia", value: "SA" },
	{ name: "Senegal", value: "SN" },
	{ name: "Serbia", value: "RS" },
	{ name: "Serbia and Montenegro", value: "CS" },
	{ name: "Seychelles", value: "SC" },
	{ name: "Sierra Leone", value: "SL" },
	{ name: "Singapore", value: "SG" },
	{ name: "Sint Maarten", value: "SX" },
	{ name: "Slovakia", value: "SK" },
	{ name: "Slovenia", value: "SI" },
	{ name: "Solomon Islands", value: "SB" },
	{ name: "Somalia", value: "SO" },
	{ name: "South Africa", value: "ZA" },
	{ name: "South Georgia and the South Sandwich Islands", value: "GS" },
	{ name: "South Sudan", value: "SS" },
	{ name: "Spain", value: "ES" },
	{ name: "Sri Lanka", value: "LK" },
	{ name: "Sudan", value: "SD" },
	{ name: "Suriname", value: "SR" },
	{ name: "Svalbard and Jan Mayen", value: "SJ" },
	{ name: "Swaziland", value: "SZ" },
	{ name: "Sweden", value: "SE" },
	{ name: "Switzerland", value: "CH" },
	{ name: "Syrian Arab Republic", value: "SY" },
	{ name: "Taiwan, Province of China", value: "TW" },
	{ name: "Tajikistan", value: "TJ" },
	{ name: "Tanzania, United Republic of", value: "TZ" },
	{ name: "Thailand", value: "TH" },
	{ name: "Timor-Leste", value: "TL" },
	{ name: "Togo", value: "TG" },
	{ name: "Tokelau", value: "TK" },
	{ name: "Tonga", value: "TO" },
	{ name: "Trinidad and Tobago", value: "TT" },
	{ name: "Tunisia", value: "TN" },
	{ name: "Turkey", value: "TR" },
	{ name: "Turkmenistan", value: "TM" },
	{ name: "Turks and Caicos Islands", value: "TC" },
	{ name: "Tuvalu", value: "TV" },
	{ name: "Uganda", value: "UG" },
	{ name: "Ukraine", value: "UA" },
	{ name: "United Arab Emirates", value: "AE" },
	{ name: "United Kingdom", value: "GB" },
	{ name: "United States", value: "US" },
	{ name: "United States Minor Outlying Islands", value: "UM" },
	{ name: "Uruguay", value: "UY" },
	{ name: "Uzbekistan", value: "UZ" },
	{ name: "Vanuatu", value: "VU" },
	{ name: "Venezuela", value: "VE" },
	{ name: "Viet Nam", value: "VN" },
	{ name: "Virgin Islands, British", value: "VG" },
	{ name: "Virgin Islands, U.s.", value: "VI" },
	{ name: "Wallis and Futuna", value: "WF" },
	{ name: "Western Sahara", value: "EH" },
	{ name: "Yemen", value: "ZE" },
	{ name: "Zambia", value: "ZM" },
	{ name: "Zimbabwe", value: "ZW" },
];
